// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: bloom.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BloomService_Add_FullMethodName    = "/bloom.BloomService/Add"
	BloomService_Exists_FullMethodName = "/bloom.BloomService/Exists"
	BloomService_Store_FullMethodName  = "/bloom.BloomService/Store"
	BloomService_Load_FullMethodName   = "/bloom.BloomService/Load"
)

// BloomServiceClient is the client API for BloomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BloomServiceClient interface {
	// 过滤
	Add(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (*ItemResponse, error)
	Exists(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (*ItemResponse, error)
	// map
	Store(ctx context.Context, in *MapRequest, opts ...grpc.CallOption) (*MapResponse, error)
	Load(ctx context.Context, in *MapRequest, opts ...grpc.CallOption) (*MapResponse, error)
}

type bloomServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBloomServiceClient(cc grpc.ClientConnInterface) BloomServiceClient {
	return &bloomServiceClient{cc}
}

func (c *bloomServiceClient) Add(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (*ItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemResponse)
	err := c.cc.Invoke(ctx, BloomService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bloomServiceClient) Exists(ctx context.Context, in *ItemRequest, opts ...grpc.CallOption) (*ItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemResponse)
	err := c.cc.Invoke(ctx, BloomService_Exists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bloomServiceClient) Store(ctx context.Context, in *MapRequest, opts ...grpc.CallOption) (*MapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MapResponse)
	err := c.cc.Invoke(ctx, BloomService_Store_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bloomServiceClient) Load(ctx context.Context, in *MapRequest, opts ...grpc.CallOption) (*MapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MapResponse)
	err := c.cc.Invoke(ctx, BloomService_Load_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BloomServiceServer is the server API for BloomService service.
// All implementations must embed UnimplementedBloomServiceServer
// for forward compatibility.
type BloomServiceServer interface {
	// 过滤
	Add(context.Context, *ItemRequest) (*ItemResponse, error)
	Exists(context.Context, *ItemRequest) (*ItemResponse, error)
	// map
	Store(context.Context, *MapRequest) (*MapResponse, error)
	Load(context.Context, *MapRequest) (*MapResponse, error)
	mustEmbedUnimplementedBloomServiceServer()
}

// UnimplementedBloomServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBloomServiceServer struct{}

func (UnimplementedBloomServiceServer) Add(context.Context, *ItemRequest) (*ItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedBloomServiceServer) Exists(context.Context, *ItemRequest) (*ItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exists not implemented")
}
func (UnimplementedBloomServiceServer) Store(context.Context, *MapRequest) (*MapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedBloomServiceServer) Load(context.Context, *MapRequest) (*MapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Load not implemented")
}
func (UnimplementedBloomServiceServer) mustEmbedUnimplementedBloomServiceServer() {}
func (UnimplementedBloomServiceServer) testEmbeddedByValue()                      {}

// UnsafeBloomServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BloomServiceServer will
// result in compilation errors.
type UnsafeBloomServiceServer interface {
	mustEmbedUnimplementedBloomServiceServer()
}

func RegisterBloomServiceServer(s grpc.ServiceRegistrar, srv BloomServiceServer) {
	// If the following call panics, it indicates UnimplementedBloomServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BloomService_ServiceDesc, srv)
}

func _BloomService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BloomServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BloomService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BloomServiceServer).Add(ctx, req.(*ItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BloomService_Exists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BloomServiceServer).Exists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BloomService_Exists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BloomServiceServer).Exists(ctx, req.(*ItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BloomService_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BloomServiceServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BloomService_Store_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BloomServiceServer).Store(ctx, req.(*MapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BloomService_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BloomServiceServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BloomService_Load_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BloomServiceServer).Load(ctx, req.(*MapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BloomService_ServiceDesc is the grpc.ServiceDesc for BloomService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BloomService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bloom.BloomService",
	HandlerType: (*BloomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _BloomService_Add_Handler,
		},
		{
			MethodName: "Exists",
			Handler:    _BloomService_Exists_Handler,
		},
		{
			MethodName: "Store",
			Handler:    _BloomService_Store_Handler,
		},
		{
			MethodName: "Load",
			Handler:    _BloomService_Load_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bloom.proto",
}
