// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bloom.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ItemRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemRequest) Reset()         { *m = ItemRequest{} }
func (m *ItemRequest) String() string { return proto.CompactTextString(m) }
func (*ItemRequest) ProtoMessage()    {}
func (*ItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_244a8f28f63f0104, []int{0}
}

func (m *ItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemRequest.Unmarshal(m, b)
}
func (m *ItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemRequest.Marshal(b, m, deterministic)
}
func (m *ItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemRequest.Merge(m, src)
}
func (m *ItemRequest) XXX_Size() int {
	return xxx_messageInfo_ItemRequest.Size(m)
}
func (m *ItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ItemRequest proto.InternalMessageInfo

func (m *ItemRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type ItemResponse struct {
	Exists               bool     `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemResponse) Reset()         { *m = ItemResponse{} }
func (m *ItemResponse) String() string { return proto.CompactTextString(m) }
func (*ItemResponse) ProtoMessage()    {}
func (*ItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_244a8f28f63f0104, []int{1}
}

func (m *ItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemResponse.Unmarshal(m, b)
}
func (m *ItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemResponse.Marshal(b, m, deterministic)
}
func (m *ItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemResponse.Merge(m, src)
}
func (m *ItemResponse) XXX_Size() int {
	return xxx_messageInfo_ItemResponse.Size(m)
}
func (m *ItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ItemResponse proto.InternalMessageInfo

func (m *ItemResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

type MapRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapRequest) Reset()         { *m = MapRequest{} }
func (m *MapRequest) String() string { return proto.CompactTextString(m) }
func (*MapRequest) ProtoMessage()    {}
func (*MapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_244a8f28f63f0104, []int{2}
}

func (m *MapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapRequest.Unmarshal(m, b)
}
func (m *MapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapRequest.Marshal(b, m, deterministic)
}
func (m *MapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapRequest.Merge(m, src)
}
func (m *MapRequest) XXX_Size() int {
	return xxx_messageInfo_MapRequest.Size(m)
}
func (m *MapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MapRequest proto.InternalMessageInfo

func (m *MapRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MapRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type MapResponse struct {
	Exists               bool     `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapResponse) Reset()         { *m = MapResponse{} }
func (m *MapResponse) String() string { return proto.CompactTextString(m) }
func (*MapResponse) ProtoMessage()    {}
func (*MapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_244a8f28f63f0104, []int{3}
}

func (m *MapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapResponse.Unmarshal(m, b)
}
func (m *MapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapResponse.Marshal(b, m, deterministic)
}
func (m *MapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapResponse.Merge(m, src)
}
func (m *MapResponse) XXX_Size() int {
	return xxx_messageInfo_MapResponse.Size(m)
}
func (m *MapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MapResponse proto.InternalMessageInfo

func (m *MapResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func (m *MapResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*ItemRequest)(nil), "bloom.ItemRequest")
	proto.RegisterType((*ItemResponse)(nil), "bloom.ItemResponse")
	proto.RegisterType((*MapRequest)(nil), "bloom.MapRequest")
	proto.RegisterType((*MapResponse)(nil), "bloom.MapResponse")
}

func init() {
	proto.RegisterFile("bloom.proto", fileDescriptor_244a8f28f63f0104)
}

var fileDescriptor_244a8f28f63f0104 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xca, 0xc9, 0xcf,
	0xcf, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0xe4, 0xb9, 0xb8, 0x3d,
	0x4b, 0x52, 0x73, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x04, 0xb8, 0x98, 0xb3, 0x53,
	0x2b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x25, 0x35, 0x2e, 0x1e, 0x88, 0x82,
	0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x31, 0x2e, 0xb6, 0xd4, 0x8a, 0xcc, 0xe2, 0x92, 0x62,
	0xb0, 0x22, 0x8e, 0x20, 0x28, 0x4f, 0xc9, 0x84, 0x8b, 0xcb, 0x37, 0xb1, 0x00, 0xa7, 0x39, 0x42,
	0x22, 0x5c, 0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x12, 0x4c, 0x60, 0x31, 0x08, 0x47, 0xc9, 0x9a,
	0x8b, 0x1b, 0xac, 0x0b, 0xbf, 0xe1, 0xd8, 0x35, 0x1b, 0x5d, 0x60, 0xe4, 0xe2, 0x71, 0x02, 0xf9,
	0x22, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0x48, 0x8f, 0x8b, 0xd9, 0x31, 0x25, 0x45, 0x48,
	0x48, 0x0f, 0xe2, 0x51, 0x24, 0x8f, 0x49, 0x09, 0xa3, 0x88, 0x41, 0xad, 0x33, 0xe4, 0x62, 0x73,
	0x85, 0x58, 0x40, 0xb4, 0x16, 0x3d, 0x2e, 0xd6, 0xe0, 0x92, 0xfc, 0xa2, 0x54, 0x21, 0x41, 0xa8,
	0x2c, 0xc2, 0xd3, 0x52, 0x42, 0xc8, 0x42, 0x50, 0xf5, 0xba, 0x5c, 0x2c, 0x3e, 0xf9, 0x89, 0x29,
	0x44, 0x2a, 0x77, 0xe2, 0x8a, 0xe2, 0xd0, 0xd3, 0xd3, 0x2f, 0x48, 0xb2, 0x2e, 0x48, 0x4a, 0x62,
	0x03, 0x47, 0x94, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x9b, 0xde, 0x29, 0xb7, 0x01, 0x00,
	0x00,
}
